post  http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRFU1RfTE9HSU4iLCJpZCI6IjYxZDcyMmY3ODZmN2ZmYTAyMjQzMGRiNyIsImlhdCI6MTY0MTQ4OTQ3NH0.FZ6smmcl_-OANmo9tPpr3VaESlP5iLlq3X3qAeAOydQ

{
  "url":"urlurlurasdwdqlurlurlurl",
  "title": "asddwdqsdasdasdfads",
  "author": "josfjosi"
}
